package se.birdy.app.ui.settings.credits

import org.junit.Test
import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Release 1.3.0, legal review 7i-fix B: the open-source licence list the app ships
 * (composeResources/files/licenses/, generated by tools/licenses/generate.py) is complete and
 * consistent. Plain JVM, run by `:composeApp:testDebugUnitTest` (CI).
 *
 * The guard against a changed dependency set has two halves. This test checks that every
 * dependency in tools/licenses/release-dependencies.txt (the list the files were generated from)
 * has an entry, that every file an entry opens exists, and that every bundled font is credited.
 * `:androidApp:verifyLicenseList` (CI, `check`, and every release bundle or APK) resolves the
 * release build's dependencies afresh and fails when they differ from that list. A JVM test cannot
 * resolve Gradle dependencies itself, hence the split.
 */
class LicenseListTest {
    private val repoRoot: File =
        generateSequence(File(System.getProperty("user.dir") ?: ".").absoluteFile) { it.parentFile }
            .first { File(it, "tools/licenses/release-dependencies.txt").isFile }
    private val licenseDir = File(repoRoot, "composeApp/src/commonMain/composeResources/files/licenses")
    private val index = parseLicenseIndex(File(licenseDir, "index.json").readText())
    private val entries = index.sections.flatMap { it.entries }

    private fun entry(id: String): LicenseEntry = assertNotNull(index.entry(id), "no entry '$id'")

    private fun text(file: String): String = File(licenseDir, file).readText()

    @Test
    fun `every release dependency has a licence entry and every library entry is a release dependency`() {
        val dependencies =
            File(repoRoot, "tools/licenses/release-dependencies.txt")
                .readLines()
                .map { it.trim() }
                .filter { it.isNotEmpty() && !it.startsWith("#") }
                .toSet()
        val covered =
            entries
                .filter { it.id.startsWith("lib:") }
                .flatMap { entry ->
                    val (group, version) = entry.id.removePrefix("lib:").split(":", limit = 2)
                    entry.artifacts.map { "$group:$it:$version" }
                }.toSet()
        assertTrue(dependencies.size > 100, "only ${dependencies.size} dependencies listed")
        assertEquals(emptySet(), dependencies - covered, "release dependencies without a licence entry")
        assertEquals(emptySet(), covered - dependencies, "licence entries for libraries the release does not have")
    }

    @Test
    fun `every entry opens a text that is there, and ids are unique`() {
        assertEquals(entries.size, entries.map { it.id }.toSet().size, "duplicate entry ids")
        val files = entries.flatMap { listOfNotNull(it.file, it.notice) }.toSet()
        for (file in files) {
            val f = File(licenseDir, file)
            assertTrue(f.isFile && f.length() > 0, "missing or empty licence file $file")
            assertTrue('\r' !in f.readText(), "$file has CR line endings")
        }
        entries.forEach { assertTrue(it.license.isNotBlank(), it.id) }
        // Only the two notice collections have no version of their own.
        entries
            .filter { it.id != NATIVE_NOTICES_ID && it.id != GOOGLE_NOTICES_ID }
            .forEach { assertTrue(it.version.isNotBlank(), it.id) }
    }

    @Test
    fun `every section has a title in the app`() {
        assertEquals(LICENSE_SECTION_IDS, index.sections.map { it.id })
        index.sections.forEach { assertNotNull(licenseSectionTitle(it.id), it.id) }
    }

    @Test
    fun `every bundled font is credited with its copyright and the open font license`() {
        val fontFiles =
            listOf("composeApp/src/commonMain/composeResources/font", "shared/pdf/src/androidMain/assets/fonts")
                .flatMap { dir -> File(repoRoot, dir).listFiles().orEmpty().filter { it.extension in setOf("ttf", "otf") } }
                .map { it.name }
                .toSet()
        val fonts = index.sections.single { it.id == "fonts" }.entries
        assertEquals(fontFiles, fonts.flatMap { it.artifacts }.toSet(), "fonts without a licence entry")
        fonts.forEach { font ->
            assertEquals("ofl-1.1.txt", font.file)
            assertTrue(font.copyright.isNotEmpty() && font.copyright.all { "Copyright" in it }, font.name)
        }
        assertTrue("SIL OPEN FONT LICENSE Version 1.1" in text("ofl-1.1.txt"))
        assertTrue("The Caveat Project Authors" in entry("font:caveat").copyright.joinToString())
        assertTrue("Adobe Systems Incorporated" in entry("font:dm-serif-display").copyright.joinToString())
    }

    @Test
    fun `the models are credited with their licences`() {
        val birdnet = entry("birdnet-lite")
        assertEquals("CC BY-NC-SA 4.0", birdnet.license)
        val birdnetText = text(birdnet.file)
        assertTrue("K. Lisa Yang Center for Conservation Bioacoustics" in birdnetText)
        assertTrue("https://creativecommons.org/licenses/by-nc-sa/4.0/" in birdnetText)
        assertTrue("Ecological Informatics, 61, 101236" in birdnetText)

        val aiy = entry("aiy-birds-v1")
        assertEquals("Apache License 2.0", aiy.license)
        assertEquals("apache-2.0.txt", aiy.file)
        assertTrue("© Google" in text(assertNotNull(aiy.notice)))
        assertTrue("Version 2.0, January 2004" in text("apache-2.0.txt"))
    }

    @Test
    fun `tensorflow comes with the caffe notice and the notices of its native code`() {
        assertTrue("Some of TensorFlow's code is derived from Caffe" in text("tensorflow.txt"))
        val native = text("tensorflow-third-party.txt")
        val components =
            Regex(""""name": "([^"]+)"""")
                .findAll(File(repoRoot, "tools/licenses/native-components.json").readText())
                .map { it.groupValues[1] }
                .toList()
        assertTrue(components.size >= 15, components.toString())
        components.forEach { assertTrue("$it\n" in native, "no notice for $it") }
        assertTrue("This software is based in part on the work of the Independent JPEG Group." in native)
        assertEquals("tensorflow.txt", entry("lib:com.google.ai.edge.litert:1.4.1").file)
    }

    /**
     * The native notices were researched for one flex library (tag and TensorFlow commit) and one
     * LiteRT version. A bump of either must send someone back to native-components.json and the
     * generator, so this fails until the two agree again.
     */
    @Test
    fun `the native notices were made for the tensorflow libraries the app ships`() {
        val manifest = File(repoRoot, "tools/licenses/native-components.json").readText()

        fun field(name: String) = assertNotNull(Regex(""""$name": "([^"]+)"""").find(manifest), name).groupValues[1]
        val build = File(repoRoot, "androidApp/build.gradle.kts").readText()
        val flexTag = assertNotNull(Regex("""val flexReleaseTag = "([^"]+)"""").find(build)).groupValues[1]
        assertEquals(field("flexTag"), flexTag, "flex library changed: update native-components.json, run generate.py")
        assertTrue(field("tensorflowCommit").startsWith(flexTag.removePrefix("tf-")), "tag and commit disagree")

        val litert = field("litertVersion")
        val declared =
            listOf("androidApp/build.gradle.kts", "shared/ml/build.gradle.kts", "gradle/libs.versions.toml")
                .map { File(repoRoot, it).readText() }
                .flatMap { text ->
                    Regex("""com\.google\.ai\.edge\.litert:litert:([0-9][^"]*)|\blitert\s*=\s*"([^"]+)"""")
                        .findAll(text)
                        .map { it.groupValues[1].ifEmpty { it.groupValues[2] } }
                        .toList()
                }
        assertTrue(declared.isNotEmpty(), "no LiteRT version found in the build files")
        assertEquals(setOf(litert), declared.toSet(), "LiteRT changed: update native-components.json, run generate.py")
        assertNotNull(index.entry("lib:com.google.ai.edge.litert:$litert"))
        assertTrue("LiteRT $litert" in text("tensorflow-third-party.txt"))
    }

    @Test
    fun `google's libraries come with the notices they carry`() {
        val google = index.sections.single { it.id == "google" }.entries
        assertTrue(google.any { it.id.startsWith("lib:com.android.billingclient:") })
        val notices = text(entry("google-third-party").file)
        listOf("Protocol Buffers", "Animal Sniffer", "Checker Framework Annotations", "JSR 305").forEach {
            assertTrue("$it\n" in notices, "no notice for $it")
        }
    }

    @Test
    fun `the licence files stay small`() {
        val total = licenseDir.listFiles().orEmpty().sumOf { it.length() }
        assertTrue(total < 600 * 1024, "licence files are ${total / 1024} KB")
    }
}
