package se.birdy.app.ui.settings.credits

import birdy_bird_scanner.composeapp.generated.resources.Res
import birdy_bird_scanner.composeapp.generated.resources.license_preface_desugar_about
import birdy_bird_scanner.composeapp.generated.resources.license_preface_desugar_config_about
import birdy_bird_scanner.composeapp.generated.resources.license_preface_desugar_config_text_source
import birdy_bird_scanner.composeapp.generated.resources.license_preface_desugar_source
import birdy_bird_scanner.composeapp.generated.resources.license_preface_desugar_text_source
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.json.Json
import org.jetbrains.compose.resources.ExperimentalResourceApi
import org.jetbrains.compose.resources.StringResource
import kotlin.concurrent.Volatile

/*
 * The open-source licence list (release 1.3.0, legal review 7i-fix B). Its files are generated by
 * tools/licenses/generate.py into composeResources/files/licenses/: index.json lists what the
 * "Licenser för öppen källkod" page shows, and each entry names the text file it opens. Never edit
 * them by hand; the generator's docstring says when and how to run it.
 */

/** index.json: the page's sections in order. */
@Serializable
internal data class LicenseIndex(
    val sections: List<LicenseSection>,
) {
    fun entry(id: String): LicenseEntry? {
        val entries = sections.flatMap { it.entries }
        return entries.firstOrNull { it.id == id }
    }
}

/** A section of the page; [id] picks its localized title (see `licenseSectionTitle`). */
@Serializable
internal data class LicenseSection(
    val id: String,
    val entries: List<LicenseEntry>,
)

/**
 * One row: a library group, a model, a font or a set of notices. [file] is the licence or notice
 * text it opens; [notice] an optional short notice file shown before it; [copyright] copyright lines
 * shown before it (fonts); [artifacts] what the entry covers (Maven artifacts, font files, native
 * components); [coordinates] a library entry's `group:name:version`s (LicenseListTest checks them
 * against the release dependencies).
 */
@Serializable
internal data class LicenseEntry(
    val id: String,
    val name: String,
    val version: String,
    val license: String,
    val file: String,
    val notice: String? = null,
    val copyright: List<String> = emptyList(),
    val artifacts: List<String> = emptyList(),
    val coordinates: List<String> = emptyList(),
    val url: String? = null,
)

/** The section ids the page knows how to title; a test checks index.json uses no other. */
internal val LICENSE_SECTION_IDS = listOf("models", "fonts", "tensorflow", "google", "libraries")

private const val LICENSE_DIR = "files/licenses/"

private val licenseJson = Json { ignoreUnknownKeys = true }

/** Parses index.json's text. */
internal fun parseLicenseIndex(text: String): LicenseIndex = licenseJson.decodeFromString<LicenseIndex>(text)

/**
 * Reads the bundled licence files, decoding and parsing off the main thread (index.json is some
 * 50 KB, the largest notice file close to 300 KB). The index is read once per process.
 */
internal object LicenseFiles {
    @Volatile
    private var cachedIndex: LicenseIndex? = null

    @OptIn(ExperimentalResourceApi::class)
    suspend fun read(file: String): String =
        withContext(Dispatchers.Default) {
            Res.readBytes(LICENSE_DIR + file).decodeToString()
        }

    suspend fun index(): LicenseIndex {
        cachedIndex?.let { return it }
        val text = read("index.json")
        return withContext(Dispatchers.Default) { parseLicenseIndex(text) }.also { cachedIndex = it }
    }
}

/**
 * What the licence text page shows for one entry. [preface]: Birdy's own lines before the licence
 * (see [LICENSE_PREFACES]), shown in the app's language.
 */
internal data class LicenseText(
    val entry: LicenseEntry,
    val notice: String?,
    val paragraphs: List<String>,
    val preface: List<StringResource> = emptyList(),
)

/**
 * Lines Birdy writes itself at the top of a licence text file (tools/licenses/generate.py,
 * LIBRARY_TEXTS' "header" and "Source of this text"), by file: the page shows these strings in the
 * app's language in place of the file's English lines. The licence text itself is never translated.
 * The English strings are the file's lines word for word (LicenseScreensTest checks it), so a new
 * text from the generator fails that test until the strings follow.
 */
internal val LICENSE_PREFACES: Map<String, List<StringResource>> =
    mapOf(
        "desugar-jdk-libs.txt" to
            listOf(
                Res.string.license_preface_desugar_about,
                Res.string.license_preface_desugar_source,
                Res.string.license_preface_desugar_text_source,
            ),
        "desugar-jdk-libs-configuration.txt" to
            listOf(
                Res.string.license_preface_desugar_config_about,
                Res.string.license_preface_desugar_config_text_source,
            ),
    )

/** [text] without its first [count] lines (the file's own preface) and the blank lines after them. */
internal fun withoutPreface(
    text: String,
    count: Int,
): String =
    text
        .replace("\r\n", "\n")
        .split('\n')
        .drop(count)
        .dropWhile { it.isBlank() }
        .joinToString("\n")

// One or more blank lines; the next paragraph keeps the indentation of its first line.
private val BLANK_LINES = Regex("\n(?:[ \t]*\n)+")

/** Longest piece of a paragraph laid out as one item; Eigen's list of files is some 18 KB. */
internal const val PARAGRAPH_CHUNK_CHARS = 2_000

/**
 * Splits a licence text into paragraphs at blank lines, and a very long paragraph into pieces at
 * line ends, so that a long text (the notices in Google's libraries are close to 300 KB) is laid out
 * lazily, a piece at a time. Call it off the main thread.
 */
internal fun licenseParagraphs(text: String): List<String> =
    text
        .replace("\r\n", "\n")
        .split(BLANK_LINES)
        .map { reflow(it.trimEnd()) }
        .filter { it.isNotBlank() }
        .flatMap(::chunked)

/** [paragraph] in pieces of at most [PARAGRAPH_CHUNK_CHARS], cut at line ends (a longer line stays whole). */
private fun chunked(paragraph: String): List<String> {
    if (paragraph.length <= PARAGRAPH_CHUNK_CHARS) return listOf(paragraph)
    val pieces = mutableListOf<String>()
    val piece = StringBuilder()
    for (line in paragraph.split('\n')) {
        if (piece.isNotEmpty() && piece.length + 1 + line.length > PARAGRAPH_CHUNK_CHARS) {
            pieces += piece.toString()
            piece.clear()
        }
        if (piece.isNotEmpty()) piece.append('\n')
        piece.append(line)
    }
    if (piece.isNotEmpty()) pieces += piece.toString()
    return pieces
}

// A line that starts a list item, a rule, a comment or a path: "1. ", "(a) ", "* ", "-----", "// ", "./".
private val STRUCTURED_LINE = Regex("""^(\d+[.)]|\([a-z0-9]+\)|[-*•=#/>|+_]|\./).*""")

// A line of its own: a copyright line, or a short "Label: value" field ("Licence: MIT").
private val OWN_LINE = Regex("""^(Copyright\b|\([Cc]\) |© |[A-Z][A-Za-z0-9 ]{0,40}: \S).*""")
private const val HEADING_MAX_LENGTH = 60

// An indented line continues the one before only after a line this long: one that was wrapped at
// the file's width (some 70 to 80 columns), not a short line of a table or a heading.
private const val WRAPPED_LINE_MIN_LENGTH = 40

/**
 * Joins the lines of a licence paragraph that were only wrapped for an 80-column file, so the text
 * wraps to the screen instead of in ragged halves. That includes indented paragraphs (the Apache
 * License's definitions, the GPL's sub-items): an indented line joins the line before it when it is
 * indented at least as deep and that line was long enough to have been wrapped. Lines that start a
 * list item, a rule, a copyright line or a "Label: value" field (indented or not), that are less
 * indented than the line before, or that follow a rule, a heading in capitals or a line ending in
 * ":" keep their own line. The words are never changed.
 */
internal fun reflow(paragraph: String): String {
    val lines = paragraph.split('\n')
    return buildString {
        lines.forEachIndexed { index, line ->
            if (index == 0) {
                append(line)
                return@forEachIndexed
            }
            val previousLine = lines[index - 1]
            val previous = previousLine.trim()
            val keepBreak =
                when {
                    line.isBlank() -> true
                    previous.endsWith(":") || previous.none { it.isLetterOrDigit() } || previous.isHeading() -> true
                    line.first().isWhitespace() -> !continuesIndented(previousLine, line)
                    else -> STRUCTURED_LINE.matches(line) || OWN_LINE.matches(line)
                }
            if (keepBreak) append('\n').append(line) else append(' ').append(line.trim())
        }
    }
}

/** Whether the indented [line] only continues [previousLine], wrapped at the file's width. */
private fun continuesIndented(
    previousLine: String,
    line: String,
): Boolean {
    val text = line.trim()
    return line.indentation() >= previousLine.indentation() &&
        previousLine.trim().length >= WRAPPED_LINE_MIN_LENGTH &&
        !STRUCTURED_LINE.matches(text) &&
        !OWN_LINE.matches(text)
}

private fun String.indentation() = indexOfFirst { !it.isWhitespace() }.let { if (it < 0) length else it }

private fun String.isHeading() = length < HEADING_MAX_LENGTH && any(Char::isLetter) && none(Char::isLowerCase)

/** The entry [id] with its notice and text, read from the bundled files and split off the main thread. */
internal suspend fun loadLicenseText(id: String): LicenseText {
    val entry = LicenseFiles.index().entry(id) ?: error("No licence entry '$id'")
    val notice = entry.notice?.let { LicenseFiles.read(it).trim() }
    val text = LicenseFiles.read(entry.file)
    val preface = LICENSE_PREFACES[entry.file].orEmpty()
    return withContext(Dispatchers.Default) {
        LicenseText(
            entry = entry,
            notice = notice,
            paragraphs = licenseParagraphs(withoutPreface(text, preface.size)),
            preface = preface,
        )
    }
}
