package se.birdy.app.ui.settings.credits

import birdy_bird_scanner.composeapp.generated.resources.Res
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.json.Json
import org.jetbrains.compose.resources.ExperimentalResourceApi

/*
 * The open-source licence list (release 1.3.0, legal review 7i-fix B). Its files are generated by
 * tools/licenses/generate.py into composeResources/files/licenses/: index.json lists what the
 * "Licenser för öppen källkod" page shows, and each entry names the text file it opens. Never edit
 * them by hand; the generator's docstring says when and how to run it.
 */

/** index.json: the page's sections in order. */
@Serializable
internal data class LicenseIndex(
    val sections: List<LicenseSection>,
) {
    fun entry(id: String): LicenseEntry? {
        val entries = sections.flatMap { it.entries }
        return entries.firstOrNull { it.id == id }
    }
}

/** A section of the page; [id] picks its localized title (see `licenseSectionTitle`). */
@Serializable
internal data class LicenseSection(
    val id: String,
    val entries: List<LicenseEntry>,
)

/**
 * One row: a library group, a model, a font or a set of notices. [file] is the licence or notice
 * text it opens; [notice] an optional short notice file shown before it; [copyright] copyright lines
 * shown before it (fonts); [artifacts] what the entry covers (Maven artifacts, font files, native
 * components).
 */
@Serializable
internal data class LicenseEntry(
    val id: String,
    val name: String,
    val version: String,
    val license: String,
    val file: String,
    val notice: String? = null,
    val copyright: List<String> = emptyList(),
    val artifacts: List<String> = emptyList(),
    val url: String? = null,
)

/** The section ids the page knows how to title; a test checks index.json uses no other. */
internal val LICENSE_SECTION_IDS = listOf("models", "fonts", "tensorflow", "google", "libraries")

private const val LICENSE_DIR = "files/licenses/"

private val licenseJson = Json { ignoreUnknownKeys = true }

/** Parses index.json's text. */
internal fun parseLicenseIndex(text: String): LicenseIndex = licenseJson.decodeFromString<LicenseIndex>(text)

/** Reads the bundled licence files. Off the main thread: the largest notice file is a few hundred KB. */
internal object LicenseFiles {
    @OptIn(ExperimentalResourceApi::class)
    suspend fun read(file: String): String =
        withContext(Dispatchers.Default) {
            Res.readBytes(LICENSE_DIR + file).decodeToString()
        }

    suspend fun index(): LicenseIndex = parseLicenseIndex(read("index.json"))
}

/** What the licence text page shows for one entry. */
internal data class LicenseText(
    val entry: LicenseEntry,
    val notice: String?,
    val paragraphs: List<String>,
)

// One or more blank lines; the next paragraph keeps the indentation of its first line.
private val BLANK_LINES = Regex("\n(?:[ \t]*\n)+")

/**
 * Splits a licence text into paragraphs at blank lines, so that a long text (the notices in
 * Google's libraries are a few hundred KB) is laid out lazily, one paragraph at a time.
 */
internal fun licenseParagraphs(text: String): List<String> =
    text
        .replace("\r\n", "\n")
        .split(BLANK_LINES)
        .map { reflow(it.trimEnd()) }
        .filter { it.isNotBlank() }

// A line that starts a list item, a rule or a comment: "1. ", "(a) ", "* ", "-----", "// ".
private val STRUCTURED_LINE = Regex("""^(\d+[.)]|\([a-z0-9]+\)|[-*•=#/>|+_]).*""")

// A line of its own: a copyright line, or a short "Label: value" field ("Licence: MIT").
private val OWN_LINE = Regex("""^(Copyright\b|\([Cc]\) |© |[A-Z][A-Za-z0-9 ]{0,40}: \S).*""")
private const val HEADING_MAX_LENGTH = 60

/**
 * Joins the lines of a licence paragraph that were only wrapped for an 80-column file, so the text
 * wraps to the screen instead of in ragged halves. Lines that are indented, start a list item, a
 * rule, a copyright line or a "Label: value" field, or follow a rule, a heading in capitals or a line
 * ending in ":" keep their own line. The words are never changed.
 */
internal fun reflow(paragraph: String): String {
    val lines = paragraph.split('\n')
    return buildString {
        lines.forEachIndexed { index, line ->
            if (index == 0) {
                append(line)
                return@forEachIndexed
            }
            val previous = lines[index - 1].trim()
            val keepBreak =
                line.isBlank() ||
                    line.first().isWhitespace() ||
                    STRUCTURED_LINE.matches(line) ||
                    OWN_LINE.matches(line) ||
                    previous.endsWith(":") ||
                    previous.none { it.isLetterOrDigit() } ||
                    previous.isHeading()
            if (keepBreak) append('\n').append(line) else append(' ').append(line.trim())
        }
    }
}

private fun String.isHeading() = length < HEADING_MAX_LENGTH && any(Char::isLetter) && none(Char::isLowerCase)

/** The entry [id] with its notice and text, read from the bundled files. */
internal suspend fun loadLicenseText(id: String): LicenseText {
    val entry = LicenseFiles.index().entry(id) ?: error("No licence entry '$id'")
    return LicenseText(
        entry = entry,
        notice = entry.notice?.let { LicenseFiles.read(it).trim() },
        paragraphs = licenseParagraphs(LicenseFiles.read(entry.file)),
    )
}
